DatasetParams:
  min_seq: 400
  max_seq: 800
  max_seq_uncond: 400
  max_text_len: 30

UncondModelParams:
  input_size: 3
  hidden_size: 400
  n_layers: 1
  num_gaussian: 20
  dropout_p: 0.2
  bi_dir: True
  bi_mode: 2
  bias: 0

AttentionUncondModelParams:
  input_size: 3
  hidden_size: 400
  n_layers: 1
  num_gaussian: 20
  dropout_p: 0.2
  bias: 0
  att_len: 50

CongenModelParams:
  input_size: 3
  hidden_size: 400
  num_gaussian: 20
  char_vec_len: 61
  dropout_p: 0.2
  n_layers: 1
  bi_dir: True
  bi_mode: 2
  num_attn_gaussian: 10
  bias: 0

TrainingParams:
  batch_size: 4
  num_workers: 0
  clip: 10.0
